name = "astrakit"
main = "src/index.js"
compatibility_date = "2024-11-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "COUNTS"
id = "48a599c20eda4b31ad3ccfaa2e865933"